config/routes.rb
Filmbase::Application.routes.draw do
  resources :rentals

  resources :box_offices

  resources :people

  resources :genres

  resources :countries

  resources :users

  resource :session, :only => [:new, :create, :destroy]

  match 'signup' => 'users#new', :as => :signup

  match 'register' => 'users#create', :as => :register

  match 'login' => 'sessions#new', :as => :login

  match 'logout' => 'sessions#destroy', :as => :logout

  match '/activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

  resources :films do
    member do
      get :rentals
      get :new_rental
    end
  end
  
    resources :rentals do
    member do
      get :box_offices
    end
  end

   root :to => "films#index"

end

app/models/rental.rb
class Rental < ActiveRecord::Base
belongs_to :country
belongs_to :film
has_many :box_offices,:order=>:created_at,:dependent=>:destroy
validates :data_start, :inclusion=>{:in=>Date.parse("12.06.1986")..Date.parse("12.09.2012")},:presence=>true
validates :film_id,:presence => true
validates :country_id,:presence => true,:uniqueness=>{:scope=>:film_id}

def er
errors.add(:data_finish, "Разница между датами должна быть больше недели")
end

end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_filter :check_admin_user, :except=>['index', 'show', 'box_offices']
  
  
  def index
    @rentals = Rental.page(params[:page])
    
    russia_id = 170
    @rus_rentals, @world_rentals = [], []
    year_now = Time.now.year
    @f = Film.all
    @f.each do |film|
      fname = film.name
      film_id = film.id
      if film.rentals.size != 0
        #  russia
        rentals = film.rentals.where(:country_id => russia_id).first
        if rentals.data_start.year == year_now
          rus = film.rentals.where(:country_id => russia_id).first.box_offices          
          if rus.size != 0
            
            rus_rental = rus.where(:number_week => rus.maximum(:number_week)).first.sum_all
            @rus_rentals << {"name" => fname,
              "sum" => rus_rental,
              "filmid" =>  film_id
            }
          end       
        end
        # world
        world_sum = 0
        film.rentals.find_each do |rental|
          if rental.data_start.year == year_now
            box_office = rental.box_offices
            if box_office.size != 0
              world_sum += box_office.where(:number_week => box_office.maximum(:number_week)).first.sum_all
            end
          end
        end
        if world_sum != 0
          @world_rentals << {"name" => fname,
            "sum" => world_sum,
            "filmid" =>  film_id
          }
        end           
      end
    end
    @rus_rentals = @rus_rentals.sort_by { |r| r["sum"]}.reverse
    @world_rentals = @world_rentals.sort_by { |r| r["sum"]}.reverse    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @rentals }
    end
  end
  
  # GET /rentals/1
  # GET /rentals/1.xml
  def show
    @rental = Rental.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @rental }
    end
  end
  
  # GET /rentals/new
  # GET /rentals/new.xml
  def new
    @rental = Rental.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @rental }
    end
  end
  
  # GET /rentals/1/edit
  def edit
    @rental = Rental.find(params[:id])
  end
  
  # POST /rentals
  # POST /rentals.xml
  def create
    @rental = Rental.new(params[:rental])
    
    a = (@rental.data_start+6.day) < @rental.data_finish 
    if a == false
      @rental.er
      render :action => "new"
      return
    end
    respond_to do |format|
      if @rental.save
        format.html { redirect_to(rentals_film_path(@rental.film), :notice => 'Сохранено') }
        format.xml  { render :xml => @rental, :status => :created, :location => @rental }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @rental.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /rentals/1
  # PUT /rentals/1.xml
  def update
    @rental = Rental.find(params[:id])
    
    respond_to do |format|
      if @rental.update_attributes(params[:rental])
        format.html { redirect_to(rentals_film_path(@rental.film), :notice => 'Дата сборов сохранена.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @rental.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  # DELETE /rentals/1
  # DELETE /rentals/1.xml
  def destroy
    @rental = Rental.find(params[:id])
    @rental.destroy

    respond_to do |format|
      format.html { redirect_to(rentals_film_path(@rental.film)) }
      format.xml  { head :ok }
    end
  end

  def box_offices
  @film = Film.full_load.find(params[:id]) 
    @box_offices = BoxOffice.where(:rental_id => Rental.where(:film_id => params[:id])).order("number_week").page(params[:page])
  end
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/views/rentals/_form.html.haml
= form_for @rental do |f|
  =f.hidden_field :film_id
  -if @rental.errors.any?
    #error_explanation
      %ul
        - @rental.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :data_start
    = f.date_select :data_start, :start_year=>1990,:end_year=>Time.now.year
  .field
    = f.label :data_finish
    = f.date_select :data_finish, :start_year=>1990,:end_year=>Time.now.year
  .field
    = f.label :country_id
    %br
    =f.select :country_id,Country.all.map{|c| [c.name,c.id]}
  .actions
    = f.submit 'Сохранить'

app/views/rentals/box_offices.html.haml
%h1=@film.name 

%table
  %tr
    %th Страна-фильм
    %th Номер недели
    %th Сумма сборов
    -if @current_user && @current_user.admin?
      %th
      %th
    
  - @box_offices.each do |box_office|
    %tr
      -country = Country.find(Rental.find(box_office.rental_id).country_id).name
      -film = Film.find(Rental.find(box_office.rental_id).film_id)       
      %td=link_to country + " - " + film.name, film

      %td= box_office.number_week
      %td= number_to_currency(box_office.sum_all, :unit => "$", :separator => ",", :delimiter => " ")
      -if @current_user && @current_user.admin?
        %td= link_to 'Редактировать', edit_box_office_path(box_office)
        %td= link_to 'Удалить', box_office, :confirm => 'Вы уверены?', :method => :delete
=paginate @box_offices
%br
= link_to "Назад", rentals_film_path(@film)

app/views/rentals/edit.html.haml
%h1 Просмотр дней сбора

= render 'form'

= link_to 'Просмотр', @rental
\|

= link_to 'Назад', rentals_film_path(@rental.film)

app/views/rentals/index.html.haml
%h1 Дни сбора
-unless @world_rentals.blank?
  %table
    %tr
      %th Фильм
      %th Сборы за последнюю неделю в мире
    -@world_rentals.each do |wr|
      %tr
        %td
          =link_to wr["name"], film_path(wr["filmid"])
        %td=number_to_currency(wr["sum"], :unit => "$", :separator => ",", :delimiter => " ")
%br      
-unless @rus_rentals.blank?  
  %table
    %tr
      %th Фильм
      %th Сборы за последнюю неделю в России
    -@rus_rentals.each do |rr|
      %tr
        %td
          =link_to rr["name"], film_path(rr["filmid"])
        %td=number_to_currency(rr["sum"], :unit => "$", :separator => ",", :delimiter => " ")
=paginate @rentals
%br
= link_to 'К списку фильмов', films_path

app/views/rentals/new.html.haml
%h1 Новая дата сборов

= render 'form'

app/views/rentals/show.html.haml
%p
  %b Дата начала:
  = @rental.data_start
%p
  %b Дата конца:
  = @rental.data_finish
%p
  %b Страна:
  = @rental.country_id
%p
  %b Фильм:
  = @rental.film_id

= link_to 'Редактировать', edit_rental_path(@rental)
\|
= link_to 'Назад', rentals_film_path(@rental.film)